# Development environment
development: # Default
    password: my-store-password
    theme_id: my-theme-id-number
    store: my-store.myshopify.com
    directory: src
    ignore_files: settings_data.json

# Production environment
production:
    password: 
    theme_id: 
    store: my-shop.myshopify.com
    directory: src
    ignore_files: settings_data.json
