# Development environment
development: # Default
    password: 
    theme_id: 
    store: my-shop.myshopify.com
    directory: src
    ignore_files: settings_data.json

# Production environment
production:
    password: 
    theme_id: 
    store: my-shop.myshopify.com
    directory: src
    ignore_files: settings_data.json
